# This file was automatically generated by RASC

# This CMake script executes RASC to regenerate project files from the current
# device configuration (as specified in configuration.xml). Typically this
# is executed as a pre-build step when the device configuration
# or preceding smart bundle of the project has changed:
#
#  cmake -P /path/to/prebuild.cmake
#
# Changing the device configuration currently also regenerates the content of
# the cmake files so this needs to run as a separate step.
#

# The directory containing this script; used to locate the configuration.xml
# and Config.cmake irrespective of the caller directory.
# REALPATH normalizes the path so it works when this script is run standalone
# (cmake -P) as well as a build pre-step, avoiding the doubled/garbled path bug.
set(SCRIPT_DIR ${CMAKE_SCRIPT_MODE_FILE}/..)
get_filename_component(RASC_CONFIG_FILE "${SCRIPT_DIR}/../configuration.xml" REALPATH)

include(${SCRIPT_DIR}/../Config.cmake)

# --- RASC generate parameters (generic, overridable) ---------------------------
# These default to this project's toolchain (LLVM/ATfE) but can be overridden per
# machine via -D on the cmake command line or environment variables, so the same
# script works on any PC without editing.
#
# RASC compiler token. Valid RASC values: GCC, LLVMARM, IAR, ARMv6, ...
if(NOT DEFINED RASC_COMPILER)
    if(DEFINED ENV{RASC_COMPILER})
        set(RASC_COMPILER $ENV{RASC_COMPILER})
    else()
        set(RASC_COMPILER "LLVMARM")
    endif()
endif()

# Toolchain version passed to RASC. Under `cmake -P` (script mode) the compiler is
# not detected, so CMAKE_C_COMPILER_VERSION is empty; fall back to a default.
if(NOT DEFINED RASC_TOOLCHAIN_VERSION)
    if(DEFINED ENV{RASC_TOOLCHAIN_VERSION})
        set(RASC_TOOLCHAIN_VERSION $ENV{RASC_TOOLCHAIN_VERSION})
    elseif(DEFINED CMAKE_C_COMPILER_VERSION AND NOT CMAKE_C_COMPILER_VERSION STREQUAL "")
        set(RASC_TOOLCHAIN_VERSION ${CMAKE_C_COMPILER_VERSION})
    else()
        set(RASC_TOOLCHAIN_VERSION "21.1.1")
    endif()
endif()

# Build configuration. Also empty under `cmake -P`; default to Debug.
if(NOT DEFINED RASC_BUILD_CONFIG)
    if(DEFINED CMAKE_BUILD_TYPE AND NOT CMAKE_BUILD_TYPE STREQUAL "")
        set(RASC_BUILD_CONFIG ${CMAKE_BUILD_TYPE})
    else()
        set(RASC_BUILD_CONFIG "Debug")
    endif()
endif()

message(STATUS "RASC generate: compiler=${RASC_COMPILER} version=${RASC_TOOLCHAIN_VERSION} config=${RASC_BUILD_CONFIG}")
message(STATUS "RASC config file: ${RASC_CONFIG_FILE}")

# NOTE: --launcher.suppressErrors is intentionally omitted. With it, RASC returns
# exit code 0 even on failure (e.g. an invalid --compiler), which would let a
# broken generate pass silently. Without it, failures propagate to RASC_EXIT_CODE.
execute_process(COMMAND ${RASC_EXE_PATH} -nosplash --generate --devicefamily ra --compiler ${RASC_COMPILER} --toolchainversion ${RASC_TOOLCHAIN_VERSION} --buildconfiguration ${RASC_BUILD_CONFIG} ${RASC_CONFIG_FILE}
    RESULT_VARIABLE RASC_EXIT_CODE)

if(NOT RASC_EXIT_CODE EQUAL "0")
    message(FATAL_ERROR "Failed to run RASC generate command")
endif()

# --- Restore #ToolchainVersion# in configuration.xml ---------------------------
# The headless RASC CLI accepts --toolchainversion for the generate step but does
# not write it back: it rewrites configuration.xml with
#     <option key="#ToolchainVersion#" value=""/>
# The e2 studio GUI, which resolves the version from its installed-toolchain
# registry, does persist it. So every VS Code regeneration blanks the field and
# shows up as a spurious diff; e2 studio may then re-prompt for a toolchain
# version when the project is opened.
#
# #SELECTED_TOOLCHAIN# (clang_arm) is left untouched by RASC, so the toolchain
# choice itself is never lost -- only the version string. Put it back here so
# configuration.xml stays consistent between the two IDEs.
file(READ "${RASC_CONFIG_FILE}" RASC_CONFIG_CONTENT)
string(REGEX REPLACE
    "(<option key=\"#ToolchainVersion#\" value=\")[^\"]*(\"/>)"
    "\\1${RASC_TOOLCHAIN_VERSION}\\2"
    RASC_CONFIG_PATCHED "${RASC_CONFIG_CONTENT}")

if(NOT RASC_CONFIG_PATCHED STREQUAL RASC_CONFIG_CONTENT)
    file(WRITE "${RASC_CONFIG_FILE}" "${RASC_CONFIG_PATCHED}")
    message(STATUS "Restored #ToolchainVersion# = ${RASC_TOOLCHAIN_VERSION} in configuration.xml")
endif()
